/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppEventosRouteImport } from './routes/app.eventos'
import { Route as AppContaRouteImport } from './routes/app.conta'
import { Route as AppAulasRouteImport } from './routes/app.aulas'
import { Route as AdminMentoradosRouteImport } from './routes/admin.mentorados'
import { Route as AdminEventosRouteImport } from './routes/admin.eventos'
import { Route as AdminEngajamentoRouteImport } from './routes/admin.engajamento'
import { Route as AdminAvaliarRouteImport } from './routes/admin.avaliar'
import { Route as AdminAulasRouteImport } from './routes/admin.aulas'
import { Route as AppAulaLessonIdRouteImport } from './routes/app.aula.$lessonId'
import { Route as AdminMentoradoIdRouteImport } from './routes/admin.mentorado.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiLessonsLessonIdStreamRouteImport } from './routes/api/lessons.$lessonId.stream'

const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppEventosRoute = AppEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AppRoute,
} as any)
const AppContaRoute = AppContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AppRoute,
} as any)
const AppAulasRoute = AppAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AppRoute,
} as any)
const AdminMentoradosRoute = AdminMentoradosRouteImport.update({
  id: '/mentorados',
  path: '/mentorados',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventosRoute = AdminEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEngajamentoRoute = AdminEngajamentoRouteImport.update({
  id: '/engajamento',
  path: '/engajamento',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvaliarRoute = AdminAvaliarRouteImport.update({
  id: '/avaliar',
  path: '/avaliar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAulasRoute = AdminAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AdminRoute,
} as any)
const AppAulaLessonIdRoute = AppAulaLessonIdRouteImport.update({
  id: '/aula/$lessonId',
  path: '/aula/$lessonId',
  getParentRoute: () => AppRoute,
} as any)
const AdminMentoradoIdRoute = AdminMentoradoIdRouteImport.update({
  id: '/mentorado/$id',
  path: '/mentorado/$id',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonsLessonIdStreamRoute =
  ApiLessonsLessonIdStreamRouteImport.update({
    id: '/api/lessons/$lessonId/stream',
    path: '/api/lessons/$lessonId/stream',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/workshop': typeof WorkshopRoute
  '/admin/aulas': typeof AdminAulasRoute
  '/admin/avaliar': typeof AdminAvaliarRoute
  '/admin/engajamento': typeof AdminEngajamentoRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/mentorados': typeof AdminMentoradosRoute
  '/app/aulas': typeof AppAulasRoute
  '/app/conta': typeof AppContaRoute
  '/app/eventos': typeof AppEventosRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/mentorado/$id': typeof AdminMentoradoIdRoute
  '/app/aula/$lessonId': typeof AppAulaLessonIdRoute
  '/api/lessons/$lessonId/stream': typeof ApiLessonsLessonIdStreamRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/workshop': typeof WorkshopRoute
  '/admin/aulas': typeof AdminAulasRoute
  '/admin/avaliar': typeof AdminAvaliarRoute
  '/admin/engajamento': typeof AdminEngajamentoRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/mentorados': typeof AdminMentoradosRoute
  '/app/aulas': typeof AppAulasRoute
  '/app/conta': typeof AppContaRoute
  '/app/eventos': typeof AppEventosRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/mentorado/$id': typeof AdminMentoradoIdRoute
  '/app/aula/$lessonId': typeof AppAulaLessonIdRoute
  '/api/lessons/$lessonId/stream': typeof ApiLessonsLessonIdStreamRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/workshop': typeof WorkshopRoute
  '/admin/aulas': typeof AdminAulasRoute
  '/admin/avaliar': typeof AdminAvaliarRoute
  '/admin/engajamento': typeof AdminEngajamentoRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/mentorados': typeof AdminMentoradosRoute
  '/app/aulas': typeof AppAulasRoute
  '/app/conta': typeof AppContaRoute
  '/app/eventos': typeof AppEventosRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/mentorado/$id': typeof AdminMentoradoIdRoute
  '/app/aula/$lessonId': typeof AppAulaLessonIdRoute
  '/api/lessons/$lessonId/stream': typeof ApiLessonsLessonIdStreamRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/set-password'
    | '/workshop'
    | '/admin/aulas'
    | '/admin/avaliar'
    | '/admin/engajamento'
    | '/admin/eventos'
    | '/admin/mentorados'
    | '/app/aulas'
    | '/app/conta'
    | '/app/eventos'
    | '/admin/'
    | '/app/'
    | '/admin/mentorado/$id'
    | '/app/aula/$lessonId'
    | '/api/lessons/$lessonId/stream'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/set-password'
    | '/workshop'
    | '/admin/aulas'
    | '/admin/avaliar'
    | '/admin/engajamento'
    | '/admin/eventos'
    | '/admin/mentorados'
    | '/app/aulas'
    | '/app/conta'
    | '/app/eventos'
    | '/admin'
    | '/app'
    | '/admin/mentorado/$id'
    | '/app/aula/$lessonId'
    | '/api/lessons/$lessonId/stream'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/set-password'
    | '/workshop'
    | '/admin/aulas'
    | '/admin/avaliar'
    | '/admin/engajamento'
    | '/admin/eventos'
    | '/admin/mentorados'
    | '/app/aulas'
    | '/app/conta'
    | '/app/eventos'
    | '/admin/'
    | '/app/'
    | '/admin/mentorado/$id'
    | '/app/aula/$lessonId'
    | '/api/lessons/$lessonId/stream'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetPasswordRoute: typeof SetPasswordRoute
  WorkshopRoute: typeof WorkshopRoute
  ApiLessonsLessonIdStreamRoute: typeof ApiLessonsLessonIdStreamRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/eventos': {
      id: '/app/eventos'
      path: '/eventos'
      fullPath: '/app/eventos'
      preLoaderRoute: typeof AppEventosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conta': {
      id: '/app/conta'
      path: '/conta'
      fullPath: '/app/conta'
      preLoaderRoute: typeof AppContaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/aulas': {
      id: '/app/aulas'
      path: '/aulas'
      fullPath: '/app/aulas'
      preLoaderRoute: typeof AppAulasRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/mentorados': {
      id: '/admin/mentorados'
      path: '/mentorados'
      fullPath: '/admin/mentorados'
      preLoaderRoute: typeof AdminMentoradosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eventos': {
      id: '/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AdminEventosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/engajamento': {
      id: '/admin/engajamento'
      path: '/engajamento'
      fullPath: '/admin/engajamento'
      preLoaderRoute: typeof AdminEngajamentoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avaliar': {
      id: '/admin/avaliar'
      path: '/avaliar'
      fullPath: '/admin/avaliar'
      preLoaderRoute: typeof AdminAvaliarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/aulas': {
      id: '/admin/aulas'
      path: '/aulas'
      fullPath: '/admin/aulas'
      preLoaderRoute: typeof AdminAulasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/aula/$lessonId': {
      id: '/app/aula/$lessonId'
      path: '/aula/$lessonId'
      fullPath: '/app/aula/$lessonId'
      preLoaderRoute: typeof AppAulaLessonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/mentorado/$id': {
      id: '/admin/mentorado/$id'
      path: '/mentorado/$id'
      fullPath: '/admin/mentorado/$id'
      preLoaderRoute: typeof AdminMentoradoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lessons/$lessonId/stream': {
      id: '/api/lessons/$lessonId/stream'
      path: '/api/lessons/$lessonId/stream'
      fullPath: '/api/lessons/$lessonId/stream'
      preLoaderRoute: typeof ApiLessonsLessonIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAulasRoute: typeof AdminAulasRoute
  AdminAvaliarRoute: typeof AdminAvaliarRoute
  AdminEngajamentoRoute: typeof AdminEngajamentoRoute
  AdminEventosRoute: typeof AdminEventosRoute
  AdminMentoradosRoute: typeof AdminMentoradosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminMentoradoIdRoute: typeof AdminMentoradoIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAulasRoute: AdminAulasRoute,
  AdminAvaliarRoute: AdminAvaliarRoute,
  AdminEngajamentoRoute: AdminEngajamentoRoute,
  AdminEventosRoute: AdminEventosRoute,
  AdminMentoradosRoute: AdminMentoradosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminMentoradoIdRoute: AdminMentoradoIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAulasRoute: typeof AppAulasRoute
  AppContaRoute: typeof AppContaRoute
  AppEventosRoute: typeof AppEventosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAulaLessonIdRoute: typeof AppAulaLessonIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAulasRoute: AppAulasRoute,
  AppContaRoute: AppContaRoute,
  AppEventosRoute: AppEventosRoute,
  AppIndexRoute: AppIndexRoute,
  AppAulaLessonIdRoute: AppAulaLessonIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetPasswordRoute: SetPasswordRoute,
  WorkshopRoute: WorkshopRoute,
  ApiLessonsLessonIdStreamRoute: ApiLessonsLessonIdStreamRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
